---
abstract: 'Useful set for work with HTTP'
author:
  - 'Mons Anderson <mons@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.62, CPAN::Meta::Converter version 2.150010'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: HTTP-Easy
no_index:
  directory:
    - t
    - inc
requires: {}
version: '0.04'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
